[IV-24-25] Objetivo_2
ChinChainis/Proyecto_Reparahorarios_IV2425 pull request #11
Opened 2024-11-07 08:40 UTC by blancagiron

# Sobre la estructura del repositorio
---
* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?
---
# Sobre el planteamiento
---
* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?
---
# Sobre el análisis del problema
---
* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.
---
# Sobre el código
---
* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [x] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-11-15 10:43 UTC, blancagiron commented
@ChinChainis me lo puedes revisar? :)

2024-11-15 12:11 UTC, ChinChainis commented
* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [X] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [X] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [X] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [X] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-15 12:25 UTC, ChinChainis commented
https://github.com/blancagiron/Proyecto_Reparahorarios_IV2425/blob/1541fd80a123ab4cb541a56772f5f5f44514924f/models/estudiantes.go#L20 Estoy probando su compilación y creo que no tienes importado el paquete fmt para este error, no sé si quieres usar el paquete errors o importar fmt

2024-11-15 12:33 UTC, blancagiron commented
Si ha sido un error porque he usado fmt para mostrar el mensaje de error pero se me ha olvidado importarlo, voy a cambiarlo y eliminar "errors"

2024-11-15 12:42 UTC, blancagiron commented
ya lo he arreglado y compila, podrías añadir el PR y los issues al M0?

2024-11-15 13:25 UTC, ChinChainis commented
Disculpa la tardanza ya los he asignado, aún sigo haciendo la build en go desde mi ordenador, grupo.go al ser el único que no usa structs de otros archivos compila bien pero el resto tienen problemas al usar de otros. ¿Tú tienes problema para compilarlos?

2024-11-15 15:39 UTC, blancagiron commented
He resuelto los problemas cambiando la versión de go en el archivo [go.mod](https://github.com/blancagiron/Proyecto_Reparahorarios_IV2425/blob/Objetivo_2/go.mod#L3) y ahora no tengo problemas para compilar

2024-11-15 15:55 UTC, ChinChainis commented
@JJ listo para revisión

2024-11-18 08:24 UTC, JJ commented
1. Debe pedir revisión ella, no tú
2. Tienes que aprobar explícitamente aparte de seguir la lista de comprobación.

2024-11-18 08:30 UTC, JJ requested changes
Aparte de las cuestiones puntuales, sería conveniente que @ChinChainis pensara cómo puede usar esto para ver si el modelo está completo o no. ¿Qué entidad usaría?

2024-11-18 08:30 UTC, JJ commented on models/asignatura.go
> +		Creditos: creditos,
¿Dónde habla en #13 de "créditos"?

2024-11-18 08:30 UTC, JJ commented on models/estudiantes.go
> +type Estudiante struct {
¿Esto es un objeto valor?

2024-11-18 08:30 UTC, JJ commented on models/horario.go
> +	HoraInicio time.Time
¿Puede ser las 3:33:21 del 15 de octubre de 1037?

2024-11-18 08:30 UTC, JJ commented on models/horario.go
> +	HoraFin    time.Time
¿Puede ser 10 minutos antes que la hora anterior?

2024-11-18 08:30 UTC, JJ commented on models/horario.go
> +		return nil, errors.New("la hora de inicio no puede ser posterior a la hora de fin")
¿Y no será más eficiente si lo codificas en el tipo?

2024-11-18 08:30 UTC, JJ commented on models/horario.go
> +func (h *Horario) ConflictoCon(other *Horario) bool {
¿Esto forma parte del modelo? ¿Se llama desde algún sitio?

2024-11-18 08:30 UTC, JJ commented on models/validaciones.go
> +func ValidarConflictosDeHorario(estudiante *Estudiante) error {
¿Las funciones forman parte del modelo?

2024-11-18 09:29 UTC, ChinChainis commented on models/horario.go
> +	HoraInicio time.Time
Es cierto que solo se necesita atributo hora, se revisará el struct.

2024-11-18 09:33 UTC, ChinChainis commented on models/horario.go
> +	HoraFin    time.Time
No entiendo esta pregunta pero si se refiere a la duración creo que una asignatura no tiene por qué durar una hora o media, así que con establecer el comienzo y el final puede servir para definirla.

2024-11-18 09:37 UTC, ChinChainis commented on models/horario.go
> +func (h *Horario) ConflictoCon(other *Horario) bool {
Se llama en validaciones.go

2024-11-21 08:51 UTC, JJ approved these changes
👍

2024-11-21 08:51 UTC, JJ commented on models/grupo.go
> +		Nombre:  nombre,
¿Será letra y no nombre?
¿Será curso y letra y no nombre?

2024-11-21 08:51 UTC, JJ commented on models/grupo.go
> +		Nombre:  nombre,
Pero esto se referiría más al nombre de la variable, porque realmente no se van a manejar de forma separada el curso y la letra.

2024-11-21 14:57 UTC, ChinChainis approved these changes

2024-11-21 14:59 UTC, ChinChainis commented
Apruebo el pull request, gracias por la revisión. :+1:

2024-11-28 07:35 UTC, merged